### ISSUE TITLE
Code review and deployment troubleshooting

### ISSUE THREAD

**Issue by andybondar** [Arina-Zap/containerized-app-example#2]
Incorrect `targetPort` [here](https://github.com/Arina-Zap/containerized-app-example/blob/ac1fc144e53894a1b12f956261c64a06263e6c1c/k8s/nginx_svc.yaml#L12). Must be:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: cc-svc
  namespace: nginx
spec:
  selector:
    app: cc-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
```

In the `README.md`, this part:
```
After a while, the last command will show the Service's external IP: af7c752d7e44b4d90ac727508c8993c2-1781732280.us-east-2.elb.amazonaws.com.

Now we can use this URL to access the App.
```

better replace with something like:
```
After a while, the last command will show the Service's external IP (or FQDN if it is a EKS Kubnernetes cluster). See the `EXTERNAL IP` field.
```
